branch-defaults:
  develop:
    environment: admindjangoqa-dev
environment-defaults:
  admindjangoqa-dev:
    branch: develop
    repository: origin-admin
global:
  application_name: AdminDjangoQA
  branch: develop
  default_ec2_keyname: KeyQA
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  no-verify-ssl: true
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin-admin
  sc: git
  workspace_type: Application
